### ISSUE TITLE
Hot-reload issue

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/app-template-default#10]
Referecing https://github.com/quasarframework/quasar/issues/312

**Comment by Vaerum** [comment]
I found the solution/problem. The problem is not caused by the Quasar framework.
Found the solution in this thread: https://github.com/glenjamin/webpack-hot-middleware/issues/129

If I run **sudo quasar dev** it will work. It something about the permission in the project folder. The thread suggest to run this command in the project folder to skipe the sudo command:
`sudo chown -R `whoami`: .`

The command have not worked for me. I will continue to use the sudo command until I have found the problem with my OS.

//Rasmus

**Comment by rstoenescu** [comment]
Thanks for following this and adding the solution you found! I appreciate it!

**Comment by rstoenescu** [comment]
Will document this particular case in the docs.

**Comment by hawkeye64** [comment]
Adding this for anyone else in the future that runs into this issues. 

I just created a Quasar app and had the exact same issue. Apparently, depending on various settings between Ubuntu versions, you may get different results as this happens to be a file watcher issue. I found this information: [File system monitoring issue](https://wiki.archlinux.org/index.php/dropbox#Filesystem_monitoring_problem)

To temporarily fix, you can run this:
`echo 100000 | sudo tee /proc/sys/fs/inotify/max_user_watches`

Or, for a more permanent result, you can edit 
`/etc/sysctl.d/99-sysctl.conf`

and add:
`fs.inotify.max_user_watches = 100000`

then reload the kernel parameters with:
`sysctl --system`

**Comment by abhijit-padhy** [comment]
Try adding ` -- --reset-cache` to your run command. 
*for Linux OS

Ref: 
https://www.reddit.com/r/reactnative/comments/8mlelt/hot_reloadinglive_reload_stopped_working_how_do_i/
