### ISSUE TITLE
Allow dots in webpack server in Quasar v15+

### ISSUE THREAD

**Issue by roccolangeweg-old** [quasarframework/app-template-default#56]
### Software version

Quasar: 16
OS: MacOS
Node: v9.4.0
NPM: 6.1.0
Browsers: Chrome / ALL
iOS: -
Android: -
Any other software related to your bug:

### What did you get as the error?

With the abstraction of webpack config's into quasar.conf.js, there is no option to add webpack rules to `disableDotRule` for the history fallback, this makes it unable to use certain params (such as JWT tokens or e-mailadresses (encoded)) as params.

### What were you expecting?

I'm expecting a file to be available to add the following snippet:
```
app.use(require('connect-history-api-fallback')({
  disableDotRule: true,
  rewrites: [
    {from: /\/app.js/, to: '/app.js'}
  ]
}))
```

### What steps did you take, to get the error?

I tried to apply above script in quasar.conf.js but there is currently no way to get this working.

**Comment by smolinari** [comment]
I think you've got this in the wrong repo. This template is deprecated since version 0.15. You'll most likely get an answer here, but to be certain, you might want to add your issue to either the [core repo](https://github.com/quasarframework/quasar) or [the starter-kit](
https://github.com/quasarframework/quasar-starter-kit).

Scott

**Comment by smolinari** [comment]
Since you did open a new issue. Can you close this one?

Thanks!

Scott

**Comment by rstoenescu** [comment]
I remember I answered this already. But yes, wrong repo.
